# Generated by Django 4.2.11 on 2024-09-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historialcarrito',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
        migrations.DeleteModel(
            name='Facturacion',
        ),
        migrations.DeleteModel(
            name='HistorialCarrito',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
